ALTER TABLE models ADD COLUMN developer TEXT NOT NULL DEFAULT '';
ALTER TABLE models ADD COLUMN model_type TEXT NOT NULL DEFAULT 'llm';
ALTER TABLE models ADD COLUMN input_price REAL NOT NULL DEFAULT 0;
ALTER TABLE models ADD COLUMN output_price REAL NOT NULL DEFAULT 0;
